from pxr import Usd, UsdGeom, Sdf, Vt, Gf
stage = Usd.Stage.CreateInMemory()
UsdGeom.SetStageUpAxis(stage, UsdGeom.Tokens.z)
root = UsdGeom.Xform.Define(stage, "/World")
mesh = UsdGeom.Mesh.Define(stage, "/World/Quad")
pts = [(0, 0, 0), (1, 0, 0), (1, 1, 0), (0, 1, 0)]
mesh.CreatePointsAttr(pts)
mesh.CreateFaceVertexCountsAttr([4])
mesh.CreateFaceVertexIndicesAttr([0, 1, 2, 3])
mesh.CreateExtentAttr(UsdGeom.PointBased.ComputeExtent(pts))
mesh.GetPointsAttr().Set([(0, 0, 0), (5, 0, 0), (5, 5, 0), (0, 5, 0)])
pv = UsdGeom.PrimvarsAPI(mesh).CreatePrimvar(
    "displayColor", Sdf.ValueTypeNames.Color3fArray, UsdGeom.Tokens.vertex)
pv.Set([(1, 0, 0), (0, 1, 0)])
guide = UsdGeom.Cube.Define(stage, "/World/Helper")
guide.CreatePurposeAttr(UsdGeom.Tokens.guide)
hidden = UsdGeom.Sphere.Define(stage, "/World/Hidden")
root.GetPrim()
UsdGeom.Imageable(stage.GetPrimAtPath("/World")).GetVisibilityAttr()
hidden.CreateVisibilityAttr(UsdGeom.Tokens.invisible)
print(mesh.ValidateTopology([0, 1, 2, 3], [4], 4))
print(UsdGeom.Imageable(hidden).ComputeVisibility(), UsdGeom.Imageable(guide).ComputePurpose())
print(pv.GetInterpolation(), len(pv.Get()), pv.GetElementSize())
print(mesh.GetFaceCount() if hasattr(mesh, 'GetFaceCount') else 'nofc')
