from pxr import Tf, UsdUtils, Usd, Sdf
d = UsdUtils.CoalescingDiagnosticDelegate()
for i in range(3):
    Tf.Warn("same msg %d" % i)
Tf.Status("st")
cd = d.TakeCoalescedDiagnostics()
for x in cd:
    print([n for n in dir(x.sharedItem) if not n.startswith('_')])
    print(x.sharedItem.sourceFunction, x.sharedItem.sourceLineNumber)
    print([u.commentary for u in x.unsharedItems], [n for n in dir(x.unsharedItems[0]) if not n.startswith('_')])
print("again", len(d.TakeCoalescedDiagnostics()))
for i in range(3):
    Tf.Warn("same msg %d" % i)
print("---dump")
d.DumpCoalescedDiagnosticsToStdout()
print("---end")
print(Tf.Debug.GetDebugSymbolNames()[:5], len(Tf.Debug.GetDebugSymbolNames()))
names = Tf.Debug.GetDebugSymbolNames()
print([n for n in names if n.startswith('USD_')])
print([n for n in names if n.startswith('PCP')])
print([n for n in names if n.startswith('AR')])
print([n for n in names if n.startswith('SDF')])
print(Tf.Debug.GetDebugSymbolDescription("USD_CHANGES"))
print(Tf.Debug.IsDebugSymbolNameEnabled("USD_CHANGES"))
r = Tf.Debug.SetDebugSymbolsByName("USD_CHANGES", True)
print("ret", r, Tf.Debug.IsDebugSymbolNameEnabled("USD_CHANGES"))
r = Tf.Debug.SetDebugSymbolsByName("USD_*", False)
print("ret", r)
help(Tf.Debug.SetOutputFile)
