from pxr import Usd, Sdf
s = Usd.Stage.CreateInMemory()
a = s.DefinePrim("/A").CreateAttribute("x", Sdf.ValueTypeNames.Double)
a.Set(0.0, 0); a.Set(10.0, 10); a.Set(100.0, 20)
s.SetInterpolationType(Usd.InterpolationTypeHeld)
print(s.GetRootLayer().ExportToString())
pt = Usd.TimeCode.PreTime(10)
print(pt, pt.IsPreTime(), a.Get(pt), a.Get(10))
s.SetInterpolationType(Usd.InterpolationTypeLinear)
print(a.Get(pt), a.Get(10), a.Get(Usd.TimeCode.PreTime(15)))
